apiVersion: v1
kind: Service
metadata:
  name: argocd-server-nodeport
  namespace: argocd
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
spec:
  type: NodePort
  selector:
    # Dieser Selector muss exakt auf die Labels des ArgoCD-Server Pods passen
    app.kubernetes.io/name: argocd-server
  ports:
    - name: http
      port: 80
      targetPort: 8080    # Der Port, auf dem der Container intern lauscht
      nodePort: 30007     # Dein fester Port für HTTP
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8080    # ArgoCD nutzt oft 8080 für beides (internes Management)
      nodePort: 30008     # Dein fester Port für HTTPS
      protocol: TCP