apiVersion: apps/v1
kind: Deployment
metadata:
  name: meine-app-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meine-web-app
  template:
    metadata:
      labels:
        app: meine-web-app
    spec:
      containers:
      - name: mein-container
        image: meisterholger/python-helloworld:v14
        ports:
        - containerPort: 5000