apiVersion: apps/v1
kind: Deployment
metadata:
  name: meine-app-deployment
  namespace: default
spec:
  replicas: 2        # Startet zwei Instanzen deines Containers für Ausfallsicherheit
  selector:
    matchLabels:
      app: meine-web-app
  template:
    metadata:
      labels:
        app: meine-web-app
    spec:
      containers:
      - name: mein-container
        image: meisterholger/python-helloworld:latest  # <--- HIER DEIN IMAGE EINTRAGEN
        ports:
        - containerPort: 5000                           # Der Port, auf dem deine App im Docker-Container lauscht
---
apiVersion: v1
kind: Service
metadata:
  name: meine-app-service
  namespace: default
spec:
  selector:
    app: meine-web-app
  ports:
    - protocol: TCP
      port: 80         # Port des Services
      targetPort: 5000   # Port des Containers
  type: ClusterIP      # Interne Erreichbarkeit im Cluster