## Application metadata
app:
  name: python-helloworld
  version: "1.0"

## Namespace configuration
namespace:
  name: test

## Deployment configuration
deployment:
  replicaCount: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  
  image:
    repository: meisterholger/python-helloworld
    tag: v15
    pullPolicy: IfNotPresent
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

## Service configuration
service:
  name: python-helloworld
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30080